from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        p = MainWindow.palette()
        p.setColor(MainWindow.backgroundRole(), QtCore.Qt.lightGray)
        MainWindow.setPalette(p)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(815, 140, 191, 16))
        self.label.setObjectName("label")
        self.clear_student_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_student_button.setGeometry(QtCore.QRect(10, 450, 391, 32))
        self.clear_student_button.setObjectName("clear_publisher_button")
        self.clear_lab_work_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_lab_work_button.setGeometry(QtCore.QRect(410, 450, 391, 32))
        self.clear_lab_work_button.setObjectName("clear_lab_work_button")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(1115, 164, 81, 24))
        self.search_button.setObjectName("search_button")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(810, 160, 300, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.data_to_delete = QtWidgets.QLineEdit(self.layoutWidget)
        self.data_to_delete.setObjectName("data_to_delete")
        self.horizontalLayout_7.addWidget(self.data_to_delete)
        self.delete_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_7.addWidget(self.delete_button)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(815, 208, 391, 18))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(810, 228, 391, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.student_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.student_name.setObjectName("student_name")
        self.horizontalLayout_2.addWidget(self.student_name)
        self.student_studentID = QtWidgets.QLineEdit(self.layoutWidget2)
        self.student_studentID.setObjectName("student_studentID")
        self.horizontalLayout_2.addWidget(self.student_studentID)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 791, 430))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student_table = QtWidgets.QTableWidget(self.layoutWidget3)
        self.student_table.setObjectName("student_table")
        self.student_table.setColumnCount(0)
        self.student_table.setRowCount(0)
        self.horizontalLayout.addWidget(self.student_table)
        self.lab_work_table = QtWidgets.QTableWidget(self.layoutWidget3)
        self.lab_work_table.setObjectName("theme_table")
        self.lab_work_table.setColumnCount(0)
        self.lab_work_table.setRowCount(0)
        self.horizontalLayout.addWidget(self.lab_work_table)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(810, 314, 391, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab_work_title = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lab_work_title.setObjectName("discipline")
        self.horizontalLayout_3.addWidget(self.lab_work_title)
        self.lab_work_discipline = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lab_work_discipline.setObjectName("author")
        self.horizontalLayout_3.addWidget(self.lab_work_discipline)
        self.lab_work_student = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lab_work_student.setObjectName("theme")
        self.horizontalLayout_3.addWidget(self.lab_work_student)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(815, 293, 391, 18))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.layoutWidgetAddingData1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidgetAddingData1.setGeometry(QtCore.QRect(810, 250, 391, 30))
        self.layoutWidgetAddingData1.setObjectName("layoutWidgetAddingData1")
        self.horizontalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidgetAddingData1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_to_student_button = QtWidgets.QPushButton(self.layoutWidgetAddingData1)
        self.add_to_student_button.setObjectName("add_to_student_button")
        self.horizontalLayout_6.addWidget(self.add_to_student_button)
        self.layoutWidgetAddingData = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidgetAddingData.setGeometry(QtCore.QRect(810, 340, 391, 30))
        self.layoutWidgetAddingData.setObjectName("layoutWidgetAddingData")
        self.horizontalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidgetAddingData)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_6")
        self.add_to_lab_work_button = QtWidgets.QPushButton(self.layoutWidgetAddingData)
        self.add_to_lab_work_button.setObjectName("add_to_lab_work_button")
        self.horizontalLayout_10.addWidget(self.add_to_lab_work_button)
        self.layoutWidget7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(900, 374, 300, 200))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.delete_database_button = QtWidgets.QPushButton(self.layoutWidget7)
        self.delete_database_button.setObjectName("delete_database_button")
        self.verticalLayout.addWidget(self.delete_database_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionDelete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "БД с работами студентов"))
        self.label.setText(_translate("MainWindow", "Введите номер студенческого билета"))
        self.clear_student_button.setText(_translate("MainWindow", "Очистить все записи о студентах"))
        self.clear_lab_work_button.setText(_translate("MainWindow", "Очистить все записи о работах"))
        self.search_button.setText(_translate("MainWindow", "Поиск"))
        self.delete_button.setText(_translate("MainWindow", "Удалить"))
        self.label_2.setText(_translate("MainWindow", "Введите имя студента"))
        self.label_3.setText(_translate("MainWindow", "Введите номер студ. билета"))
        self.label_4.setText(_translate("MainWindow", "Заголовок"))
        self.label_5.setText(_translate("MainWindow", "Дисциплина"))
        self.label_6.setText(_translate("MainWindow", "Автор"))
        self.add_to_student_button.setText(_translate("MainWindow", "Добавить новую запись о студенте"))
        self.add_to_lab_work_button.setText(_translate("MainWindow", "Добавить новую запись о работе"))
        self.delete_database_button.setText(_translate("MainWindow", "Удалить базу данных"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionDelete.setText(_translate("MainWindow", "Удалить"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Backspace"))